name: Flatpak CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flatpak:
    name: "Flatpak Build"
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:47
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        dnf install -y flatpak-builder

    - name: Build Flatpak
      run: |
        flatpak-builder --no-repo --prefix=/app build dev.jamesq.Pasar.json
